/-
Copyright (c) 2026 Jun Yin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jun Yin
-/
import RBM1D.Gauss.RowIndep
import RBM1D.Gauss.Generator

/-!
# `E_k` = integration over the `k`-th row, and strict independence of `G^(k)`

Formalization of Horng-Tzer Yau and Jun Yin, *Delocalization of One-Dimensional Random Band
Matrices*: the conditional expectation `E_k[·] = E[· | H^{(k)}]` of Section 4, in the product
model of `RBM1D/Gauss/Model.lean`.

In that model the sample space is an honest product, `Ω d = Coord d → ℝ` with
`P d = Measure.infinitePi (fun c ↦ gaussianReal 0 (gvar d c))`, and the σ-algebra generated by
`H^{(k)}` is exactly the one generated by the coordinates **outside** row `k`.  So `E_k` is not
an abstract `MeasureTheory.condExp` at all: it is the integral over the row-`k` coordinates with
the others frozen,

  `E_k[X](ω) = ∫ X (rowSplit k ω ω') dP(ω')`,

where `rowSplit k ω ω'` takes the row-`k` coordinates from `ω'` and all the others from `ω`.
**No `condExp` is used anywhere in this file**, and no a.e. statement appears: all the algebra
below holds *pointwise* in `ω`.

## The four facts the fluctuation-averaging argument needs

* `RBM.Gauss.condRow_condRow` — `E_k ∘ E_k = E_k`, idempotence.  Needs *no* hypothesis at all:
  it is `rowSplit_rowSplit` plus `∫ const = const`.
* `RBM.Gauss.condRow_sub_condRow` — **`E_k ∘ (1 - E_k) = 0`**.  This is the whole basis of the
  vanishing lemma (T86).
* `RBM.Gauss.condRow_mul_of_finDepOffRow` — a factor that does not read row `k` comes out:
  `E_k[X · Y] = X · E_k[Y]`.
* `RBM.Gauss.integral_condRow` — `E[E_k X] = E[X]`, the tower property.  This is the one
  statement that is a genuine Fubini, and it rests on
  `RBM.Gauss.measurePreserving_rowSplit`: `(ω, ω') ↦ rowSplit k ω ω'` pushes `P ⊗ P` forward
  to `P`.

## Strict independence of `G^(k)` from row `k`

`RBM.Gauss.FinDepOffRow d N k g` says: `g` reads only finitely many Gaussian coordinates, and
**none of them is a row-`k` coordinate**.  This is the "strictly independent of row `k`"
hypothesis in the form the moment computations of T81/T82/T86 consume; it is strictly stronger
than `RBM.Gauss.FinDep` (`RBM.Gauss.FinDepOffRow.finDep`) and it implies both

* `RBM.Gauss.FinDepOffRow.rowSplit_eq` — `g (rowSplit k ω ω') = g ω`, and
* `RBM.Gauss.condRow_of_finDepOffRow` — `E_k[g] = g`.

The master instance is `RBM.Gauss.finDepOffRow_of_minor`: **anything** read off the minor matrix
`H_u^{(k)} = (H_u).submatrix (· ≠ k) (· ≠ k)` is `FinDepOffRow`.  In particular the minor
resolvent

  `RBM.Gauss.greenMinorMat d N u z k ω = (H_u^{(k)} - z)⁻¹`

is (`RBM.Gauss.finDepOffRow_greenMinorMat`), and so is each of its entries
(`RBM.Gauss.finDepOffRow_greenMinorMat_apply`).  Note that `greenMinorMat` is a *total*
function of `ω` — `Matrix.inv` is total — so this statement carries **no invertibility side
condition**, unlike `RBM.Gauss.greenMinor_congr_of_offRow` of `RBM1D/Gauss/RowIndep.lean`,
which it is proved from.  Where the resolvent does exist, `greenMinorMat` agrees with the
paper's `G^{(k)} = minorGreen (green H z) k` by `RBM.inv_minor_resolvent`
(`RBM.Gauss.greenMinorMat_eq_minorGreen`).

## Integrability hypotheses

Only two of the results need any:

* `RBM.Gauss.RowIntegrable d N k X` — `ω' ↦ X (rowSplit k ω ω')` is `P`-integrable for **every**
  `ω` (not merely a.e.).  This is what `E_k` needs to be additive, and it is what
  `condRow_sub_condRow` uses.  For the bounded continuous integrands of T86 it is immediate
  (`RBM.Gauss.rowIntegrable_of_continuous_of_bound`).
* `RBM.Gauss.integral_condRow` needs `Integrable X (P d)` and nothing else; the Fubini
  integrability on `P ⊗ P` is transported from it along `measurePreserving_rowSplit`.

`condRow_condRow` and `condRow_mul_of_finDepOffRow` need **no** integrability: the first is the
integral of a constant, the second is `∫ c • f = c • ∫ f`, which is unconditional in Mathlib.
-/

namespace RBM.Gauss

open MeasureTheory ProbabilityTheory Matrix

variable {d : Dims} {N : ℕ}

/-! ### The row-`k` coordinates -/

/-- The coordinate `c` belongs to **row `k` at size parameter `N`**: it is `⟨N, k, j, b⟩` or
`⟨N, j, k, b⟩` for some `j` and some tag `b`.  These are exactly the coordinates that the
entries `H_{k·}` and `H_{·k}` read, and exactly the ones `E_k` integrates out. -/
def IsRowCoord (d : Dims) (N : ℕ) (k : d.Idx N) (c : Coord d) : Prop :=
  ∃ (j : d.Idx N) (b : Bool), c = ⟨N, k, j, b⟩ ∨ c = ⟨N, j, k, b⟩

instance decidableIsRowCoord (d : Dims) (N : ℕ) (k : d.Idx N) :
    DecidablePred (IsRowCoord d N k) := fun c => by
  unfold IsRowCoord; infer_instance

/-- Membership of row `k`, read off the index triple: `⟨N, i, j, b⟩` is a row-`k` coordinate
iff `i = k` or `j = k`. -/
@[simp] theorem isRowCoord_mk (d : Dims) (N : ℕ) (k i j : d.Idx N) (b : Bool) :
    IsRowCoord d N k (⟨N, i, j, b⟩ : Coord d) ↔ (i = k ∨ j = k) := by
  constructor
  · rintro ⟨j', b', h | h⟩ <;> simp only [Sigma.mk.injEq, heq_eq_eq, Prod.mk.injEq,
      true_and] at h
    · exact Or.inl h.1
    · exact Or.inr h.2.1
  · rintro (rfl | rfl)
    · exact ⟨j, b, Or.inl rfl⟩
    · exact ⟨i, b, Or.inr rfl⟩

/-- A coordinate at a *different* size parameter is never a row-`k` coordinate. -/
theorem not_isRowCoord_of_fst_ne {k : d.Idx N} {c : Coord d} (h : c.1 ≠ N) :
    ¬ IsRowCoord d N k c := by
  rintro ⟨j, b, hc | hc⟩ <;> exact h (by rw [hc])

/-! ### Splitting a sample point along row `k` -/

/-- `rowSplit d N k ω ω'` takes the row-`k` coordinates from `ω'` and every other coordinate
from `ω`.  Integrating in `ω'` is exactly `E_k`. -/
noncomputable def rowSplit (d : Dims) (N : ℕ) (k : d.Idx N) (ω ω' : Ω d) : Ω d :=
  fun c => if IsRowCoord d N k c then ω' c else ω c

theorem rowSplit_apply_of_isRowCoord (k : d.Idx N) (ω ω' : Ω d) {c : Coord d}
    (hc : IsRowCoord d N k c) : rowSplit d N k ω ω' c = ω' c :=
  ite_eq_left hc

theorem rowSplit_apply_of_not_isRowCoord (k : d.Idx N) (ω ω' : Ω d) {c : Coord d}
    (hc : ¬ IsRowCoord d N k c) : rowSplit d N k ω ω' c = ω c :=
  ite_eq_right hc

@[simp] theorem rowSplit_self (k : d.Idx N) (ω : Ω d) : rowSplit d N k ω ω = ω := by
  funext c; unfold rowSplit; split_ifs <;> rfl

/-- **The splitting is idempotent in its first argument**: the second split overwrites exactly
the coordinates the first one wrote.  This single identity is what makes `E_k` a projection. -/
@[simp] theorem rowSplit_rowSplit (k : d.Idx N) (ω ω' ω'' : Ω d) :
    rowSplit d N k (rowSplit d N k ω ω') ω'' = rowSplit d N k ω ω'' := by
  funext c
  unfold rowSplit
  split_ifs <;> rfl

/-- `rowSplit` changes no coordinate outside row `k`; in particular `ω` and `rowSplit k ω ω'`
agree off row `k` in the sense of `RBM1D/Gauss/RowIndep.lean`. -/
theorem agreeOffRow_rowSplit (k : d.Idx N) (ω ω' : Ω d) :
    AgreeOffRow d N k ω (rowSplit d N k ω ω') := by
  intro i j b hi hj
  exact (rowSplit_apply_of_not_isRowCoord k ω ω'
    (by simp only [isRowCoord_mk]; rintro (h | h) <;> [exact hi h; exact hj h])).symm

theorem measurable_rowSplit (d : Dims) (N : ℕ) (k : d.Idx N) :
    Measurable fun p : Ω d × Ω d => rowSplit d N k p.1 p.2 := by
  refine measurable_pi_iff.2 fun c => ?_
  by_cases hc : IsRowCoord d N k c
  · have h : (fun p : Ω d × Ω d => rowSplit d N k p.1 p.2 c) = fun p => p.2 c := by
      funext p; exact rowSplit_apply_of_isRowCoord k p.1 p.2 hc
    rw [h]; exact (measurable_pi_apply c).comp measurable_snd
  · have h : (fun p : Ω d × Ω d => rowSplit d N k p.1 p.2 c) = fun p => p.1 c := by
      funext p; exact rowSplit_apply_of_not_isRowCoord k p.1 p.2 hc
    rw [h]; exact (measurable_pi_apply c).comp measurable_fst

/-! ### `(ω, ω') ↦ rowSplit k ω ω'` pushes `P ⊗ P` to `P`

This is the only measure-theoretic input of the file.  It is proved by testing on measurable
boxes: the preimage of a box splits as a product of the box restricted to the non-row
coordinates and the box restricted to the row coordinates, and `Measure.eq_infinitePi`
identifies the pushforward. -/

theorem preimage_rowSplit_pi (d : Dims) (N : ℕ) (k : d.Idx N) (s : Finset (Coord d))
    (t : Coord d → Set ℝ) :
    (fun p : Ω d × Ω d => rowSplit d N k p.1 p.2) ⁻¹' ((s : Set (Coord d)).pi t)
      = ((↑(s.filter fun c => ¬ IsRowCoord d N k c) : Set (Coord d)).pi t)
        ×ˢ ((↑(s.filter fun c => IsRowCoord d N k c) : Set (Coord d)).pi t) := by
  ext ⟨ω, ω'⟩
  simp only [Set.mem_preimage, Set.mem_pi, Set.mem_prod, Finset.mem_coe, Finset.mem_filter]
  constructor
  · intro h
    refine ⟨fun c hc => ?_, fun c hc => ?_⟩
    · have := h c hc.1
      rwa [rowSplit_apply_of_not_isRowCoord k ω ω' hc.2] at this
    · have := h c hc.1
      rwa [rowSplit_apply_of_isRowCoord k ω ω' hc.2] at this
  · rintro ⟨h1, h2⟩ c hc
    by_cases hcr : IsRowCoord d N k c
    · rw [rowSplit_apply_of_isRowCoord k ω ω' hcr]; exact h2 c ⟨hc, hcr⟩
    · rw [rowSplit_apply_of_not_isRowCoord k ω ω' hcr]; exact h1 c ⟨hc, hcr⟩

/-- **The Fubini statement behind `E_k`.**  Taking the row-`k` coordinates from one independent
copy and the rest from another reproduces the law `P d`. -/
theorem measurePreserving_rowSplit (d : Dims) (N : ℕ) (k : d.Idx N) :
    MeasurePreserving (fun p : Ω d × Ω d => rowSplit d N k p.1 p.2)
      ((P d).prod (P d)) (P d) := by
  refine ⟨measurable_rowSplit d N k, ?_⟩
  have hmeas := measurable_rowSplit d N k
  refine Measure.eq_infinitePi _ fun s t ht => ?_
  rw [Measure.map_apply hmeas (MeasurableSet.pi s.countable_toSet fun i _ => ht i),
    preimage_rowSplit_pi d N k s t, Measure.prod_prod]
  show P d _ * P d _ = _
  rw [P, Measure.infinitePi_pi _ fun i _ => ht i, Measure.infinitePi_pi _ fun i _ => ht i,
    mul_comm]
  exact Finset.prod_filter_mul_prod_filter_not s (IsRowCoord d N k) _

/-! ### The conditional expectation -/

/-- **`E_k[X] = E[X | H^{(k)}]`**, realized as the integral over the row-`k` coordinates with
all the other coordinates frozen.  This is an exact Fubini in the product model, *not* an
abstract `MeasureTheory.condExp`; in particular every identity below is pointwise in `ω`. -/
noncomputable def condRow (d : Dims) (N : ℕ) (k : d.Idx N) (X : Ω d → ℂ) : Ω d → ℂ :=
  fun ω => ∫ ω', X (rowSplit d N k ω ω') ∂(P d)

theorem condRow_apply (k : d.Idx N) (X : Ω d → ℂ) (ω : Ω d) :
    condRow d N k X ω = ∫ ω', X (rowSplit d N k ω ω') ∂(P d) := rfl

/-- `ω' ↦ X (rowSplit k ω ω')` is integrable for **every** frozen `ω`.  This is the (mild)
hypothesis under which `E_k` is additive. -/
def RowIntegrable (d : Dims) (N : ℕ) (k : d.Idx N) (X : Ω d → ℂ) : Prop :=
  ∀ ω : Ω d, Integrable (fun ω' => X (rowSplit d N k ω ω')) (P d)

theorem measurable_rowSplit_right (d : Dims) (N : ℕ) (k : d.Idx N) (ω : Ω d) :
    Measurable fun ω' : Ω d => rowSplit d N k ω ω' :=
  (measurable_rowSplit d N k).comp (measurable_const.prodMk measurable_id)

theorem rowIntegrable_of_measurable_of_bound {k : d.Idx N} {X : Ω d → ℂ} (hX : Measurable X)
    {C : ℝ} (hC : ∀ ω, ‖X ω‖ ≤ C) : RowIntegrable d N k X := fun ω =>
  Integrable.mono' (integrable_const C)
    ((hX.comp (measurable_rowSplit_right d N k ω)).aestronglyMeasurable)
    (Filter.Eventually.of_forall fun _ => hC _)

theorem rowIntegrable_of_continuous_of_bound {k : d.Idx N} {X : Ω d → ℂ} (hX : Continuous X)
    {C : ℝ} (hC : ∀ ω, ‖X ω‖ ≤ C) : RowIntegrable d N k X :=
  rowIntegrable_of_measurable_of_bound hX.measurable hC

/-! #### Idempotence and the projection identity -/

/-- `E_k` applied to a function that does not depend on `ω` at all. -/
@[simp] theorem condRow_const (k : d.Idx N) (c : ℂ) :
    condRow d N k (fun _ => c) = fun _ => c := by
  funext ω
  simp [condRow]

/-- **`E_k ∘ E_k = E_k`.**  No hypothesis: `E_k X` is already constant along row `k`, so the
second integral is the integral of a constant over a probability measure. -/
@[simp] theorem condRow_condRow (k : d.Idx N) (X : Ω d → ℂ) :
    condRow d N k (condRow d N k X) = condRow d N k X := by
  funext ω
  have h : ∀ ω' : Ω d, condRow d N k X (rowSplit d N k ω ω') = condRow d N k X ω := by
    intro ω'
    simp only [condRow, rowSplit_rowSplit]
  simp only [condRow_apply (X := condRow d N k X), h]
  simp

/-- `E_k X` does not read row `k`: it is unchanged by the splitting. -/
theorem rowSplit_condRow (k : d.Idx N) (X : Ω d → ℂ) (ω ω' : Ω d) :
    condRow d N k X (rowSplit d N k ω ω') = condRow d N k X ω := by
  simp only [condRow, rowSplit_rowSplit]

theorem condRow_sub (k : d.Idx N) {X Y : Ω d → ℂ} (hX : RowIntegrable d N k X)
    (hY : RowIntegrable d N k Y) :
    condRow d N k (fun ω => X ω - Y ω) = fun ω => condRow d N k X ω - condRow d N k Y ω := by
  funext ω
  exact integral_sub (hX ω) (hY ω)

theorem condRow_add (k : d.Idx N) {X Y : Ω d → ℂ} (hX : RowIntegrable d N k X)
    (hY : RowIntegrable d N k Y) :
    condRow d N k (fun ω => X ω + Y ω) = fun ω => condRow d N k X ω + condRow d N k Y ω := by
  funext ω
  exact integral_add (hX ω) (hY ω)

/-- **`E_k ∘ (1 - E_k) = 0`** — the identity the vanishing lemma (T86) runs on.  Only the
integrability of `X` along row `k` is needed. -/
theorem condRow_sub_condRow (k : d.Idx N) {X : Ω d → ℂ} (hX : RowIntegrable d N k X) :
    condRow d N k (fun ω => X ω - condRow d N k X ω) = 0 := by
  have hcond : RowIntegrable d N k (condRow d N k X) := by
    intro ω
    have : (fun ω' => condRow d N k X (rowSplit d N k ω ω')) = fun _ => condRow d N k X ω := by
      funext ω'; exact rowSplit_condRow k X ω ω'
    rw [this]
    exact integrable_const _
  funext ω
  rw [condRow_sub k hX hcond]
  have := congrFun (condRow_condRow k X) ω
  simp only [Pi.zero_apply, this, sub_self]

/-! #### Pulling out a factor that does not read row `k` -/

/-- **`g` is strictly independent of row `k`**: it reads only finitely many Gaussian
coordinates, and none of those is a row-`k` coordinate.

This is the shared hypothesis of the fluctuation-averaging argument: T81 and T82 use it for the
large-deviation estimates in the entries of row `k`, and T86 uses it to push `E_{k}` through a
product.  It is the `RBM.Gauss.FinDep` of `RBM1D/Gauss/Generator.lean` with the witness set
constrained to avoid row `k`. -/
def FinDepOffRow (d : Dims) (N : ℕ) (k : d.Idx N) {V : Type*} (g : Ω d → V) : Prop :=
  ∃ I : Finset (Coord d), (∀ c ∈ I, ¬ IsRowCoord d N k c) ∧
    ∀ ω ω' : Ω d, (∀ c ∈ I, ω c = ω' c) → g ω = g ω'

theorem FinDepOffRow.finDep {k : d.Idx N} {V : Type*} {g : Ω d → V}
    (h : FinDepOffRow d N k g) : FinDep d g :=
  let ⟨I, _, hI⟩ := h; ⟨I, hI⟩

/-- The defining consequence: a function strictly independent of row `k` does not see the
splitting. -/
theorem FinDepOffRow.rowSplit_eq {k : d.Idx N} {V : Type*} {g : Ω d → V}
    (h : FinDepOffRow d N k g) (ω ω' : Ω d) : g (rowSplit d N k ω ω') = g ω := by
  obtain ⟨I, hI, hg⟩ := h
  exact (hg ω _ fun c hc => (rowSplit_apply_of_not_isRowCoord k ω ω' (hI c hc)).symm).symm

theorem FinDepOffRow.comp {k : d.Idx N} {V W : Type*} {g : Ω d → V}
    (h : FinDepOffRow d N k g) (F : V → W) : FinDepOffRow d N k fun ω => F (g ω) :=
  let ⟨I, hI, hg⟩ := h
  ⟨I, hI, fun ω ω' hω => show F (g ω) = F (g ω') by rw [hg ω ω' hω]⟩

/-- A function strictly independent of row `k` is its own `E_k`. -/
theorem condRow_of_finDepOffRow {k : d.Idx N} {X : Ω d → ℂ} (h : FinDepOffRow d N k X) :
    condRow d N k X = X := by
  funext ω
  have : (fun ω' => X (rowSplit d N k ω ω')) = fun _ => X ω := by
    funext ω'; exact h.rowSplit_eq ω ω'
  simp [condRow, this]

/-- **Factors that do not read row `k` come out of `E_k`.**  No integrability hypothesis:
`∫ c • f = c • ∫ f` is unconditional. -/
theorem condRow_mul_of_finDepOffRow {k : d.Idx N} {X Y : Ω d → ℂ}
    (hX : FinDepOffRow d N k X) :
    condRow d N k (fun ω => X ω * Y ω) = fun ω => X ω * condRow d N k Y ω := by
  funext ω
  have hX' : ∀ ω', X (rowSplit d N k ω ω') = X ω := hX.rowSplit_eq ω
  simp only [condRow_apply, hX']
  exact integral_const_mul (X ω) _

/-- The mirror image, with the independent factor on the right. -/
theorem condRow_mul_of_finDepOffRow' {k : d.Idx N} {X Y : Ω d → ℂ}
    (hY : FinDepOffRow d N k Y) :
    condRow d N k (fun ω => X ω * Y ω) = fun ω => condRow d N k X ω * Y ω := by
  funext ω
  have hY' : ∀ ω', Y (rowSplit d N k ω ω') = Y ω := hY.rowSplit_eq ω
  simp only [condRow_apply, hY']
  exact integral_mul_const (Y ω) _

/-! #### The tower property `E[E_k X] = E[X]` -/

/-- **`E[E_k X] = E[X]`.**  This is the one statement that really uses Fubini, through
`measurePreserving_rowSplit`. -/
theorem integral_condRow (k : d.Idx N) {X : Ω d → ℂ} (hX : Integrable X (P d)) :
    ∫ ω, condRow d N k X ω ∂(P d) = ∫ ω, X ω ∂(P d) := by
  have hmp := measurePreserving_rowSplit d N k
  have hmap : ((P d).prod (P d)).map (fun p : Ω d × Ω d => rowSplit d N k p.1 p.2) = P d :=
    hmp.map_eq
  have hXmeas : AEStronglyMeasurable X
      (((P d).prod (P d)).map fun p : Ω d × Ω d => rowSplit d N k p.1 p.2) := by
    rw [hmap]; exact hX.aestronglyMeasurable
  have hint : Integrable (Function.uncurry fun ω ω' => X (rowSplit d N k ω ω'))
      ((P d).prod (P d)) := by
    refine (integrable_map_measure hXmeas (measurable_rowSplit d N k).aemeasurable).1 ?_
    rw [hmap]; exact hX
  have hpush := integral_map (μ := (P d).prod (P d))
    (φ := fun p : Ω d × Ω d => rowSplit d N k p.1 p.2) (f := X)
    (measurable_rowSplit d N k).aemeasurable hXmeas
  rw [hmap] at hpush
  simp only [condRow_apply]
  rw [integral_integral hint]
  exact hpush.symm

/-! ### Strict independence of the minor resolvent `G^{(k)}`

Everything read off the minor matrix `H_u^{(k)}` is `FinDepOffRow`. -/

/-- The witness set: every coordinate at size parameter `N` that is not in row `k`. -/
def offRowCoords (d : Dims) (N : ℕ) (k : d.Idx N) : Finset (Coord d) :=
  (Finset.univ.image fun p : d.Idx N × d.Idx N × Bool => (⟨N, p⟩ : Coord d)).filter
    fun c => ¬ IsRowCoord d N k c

theorem not_isRowCoord_of_mem_offRowCoords {k : d.Idx N} {c : Coord d}
    (hc : c ∈ offRowCoords d N k) : ¬ IsRowCoord d N k c :=
  (Finset.mem_filter.1 hc).2

theorem mem_offRowCoords {k i j : d.Idx N} {b : Bool} (hi : i ≠ k) (hj : j ≠ k) :
    (⟨N, i, j, b⟩ : Coord d) ∈ offRowCoords d N k := by
  refine Finset.mem_filter.2 ⟨Finset.mem_image.2 ⟨(i, j, b), Finset.mem_univ _, rfl⟩, ?_⟩
  simp only [isRowCoord_mk]
  rintro (h | h) <;> [exact hi h; exact hj h]

/-- **The master row-independence lemma.**  Anything read off the minor matrix
`H_u^{(k)} = (H_u).submatrix (· ≠ k) (· ≠ k)` is strictly independent of row `k`.  Every
"`G^{(k)}` does not see row `k`" statement of T81/T82/T86 is an instance of this. -/
theorem finDepOffRow_of_minor (d : Dims) (N : ℕ) (u : ℝ) (k : d.Idx N) {V : Type*}
    (F : Matrix {a : d.Idx N // a ≠ k} {a : d.Idx N // a ≠ k} ℂ → V) :
    FinDepOffRow d N k fun ω =>
      F ((Hflow d N u ω).submatrix (Subtype.val : {a : d.Idx N // a ≠ k} → d.Idx N)
        (Subtype.val : {a : d.Idx N // a ≠ k} → d.Idx N)) := by
  refine ⟨offRowCoords d N k, fun c hc => not_isRowCoord_of_mem_offRowCoords hc,
    fun ω ω' hω => ?_⟩
  have hagree : AgreeOffRow d N k ω ω' := fun i j b hi hj => hω _ (mem_offRowCoords hi hj)
  show F _ = F _
  rw [Hflow_submatrix_congr u hagree]

/-- The **minor resolvent** `G^{(k)} = (H_u^{(k)} - z)⁻¹`, as a *total* function of `ω`
(`Matrix.inv` is total, so no invertibility hypothesis is carried). -/
noncomputable def greenMinorMat (d : Dims) (N : ℕ) (u : ℝ) (z : ℂ) (k : d.Idx N) (ω : Ω d) :
    Matrix {a : d.Idx N // a ≠ k} {a : d.Idx N // a ≠ k} ℂ :=
  ((Hflow d N u ω).submatrix (Subtype.val : {a : d.Idx N // a ≠ k} → d.Idx N)
    (Subtype.val : {a : d.Idx N // a ≠ k} → d.Idx N)
      - z • (1 : Matrix {a : d.Idx N // a ≠ k} {a : d.Idx N // a ≠ k} ℂ))⁻¹

/-- **`G^{(k)}` is strictly independent of row `k`** — the statement T81/T82/T86 consume. -/
theorem finDepOffRow_greenMinorMat (d : Dims) (N : ℕ) (u : ℝ) (z : ℂ) (k : d.Idx N) :
    FinDepOffRow d N k (greenMinorMat d N u z k) :=
  finDepOffRow_of_minor d N u k fun M => (M - z • 1)⁻¹

/-- Entrywise form of `finDepOffRow_greenMinorMat`: each entry `G^{(k)}_{ab}` is a scalar
function of `ω` that reads no row-`k` coordinate. -/
theorem finDepOffRow_greenMinorMat_apply (d : Dims) (N : ℕ) (u : ℝ) (z : ℂ) (k : d.Idx N)
    (a b : {a : d.Idx N // a ≠ k}) :
    FinDepOffRow d N k fun ω => greenMinorMat d N u z k ω a b :=
  (finDepOffRow_greenMinorMat d N u z k).comp fun M => M a b

/-- `greenMinorMat` is the paper's `G^{(k)}`: where the full resolvent exists and
`G_{kk} ≠ 0`, it is the explicit minor formula (4.9) of `RBM1D/Green/Minor.lean`. -/
theorem greenMinorMat_eq_minorGreen (d : Dims) (N : ℕ) (u : ℝ) (z : ℂ) (k : d.Idx N) (ω : Ω d)
    (hdet : IsUnit (Hflow d N u ω - z • (1 : Matrix (d.Idx N) (d.Idx N) ℂ)).det)
    (hGkk : green (Hflow d N u ω) z k k ≠ 0) :
    greenMinorMat d N u z k ω = minorGreen (green (Hflow d N u ω) z) k :=
  inv_minor_resolvent hdet k hGkk

end RBM.Gauss
