/-
Copyright (c) 2026 Jun Yin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jun Yin
-/
import RBM1D.Gauss.PermutationFourierDoobIncrement
import RBM1D.Gauss.PermutationPrefixCellCondExp

/-!
# Real and imaginary components of actual Fourier prefix means

This module adapts the accepted complex finite-cell Fourier average and its
increment bound to the real prefix-cell means used by scalar martingale tools.
It proves no conditional MGF, tail estimate, or Gaussian local law.
-/

namespace RBM.Gauss

open MeasureTheory ProbabilityTheory
open scoped MeasureTheory

/-- The real coordinate of the actual-prefix Fourier mean, expressed as a
real prefix-cell mean. -/
noncomputable def prefixFourierRealMean (W j : ℕ) (x χ : Fin W → ℂ)
    : PermΩ W → ℝ :=
  prefixCellMean W j (fun ρ => (permutationFourierSum W x χ ρ).re)

/-- The imaginary coordinate of the actual-prefix Fourier mean, expressed as
a real prefix-cell mean. -/
noncomputable def prefixFourierImagMean (W j : ℕ) (x χ : Fin W → ℂ)
    : PermΩ W → ℝ :=
  prefixCellMean W j (fun ρ => (permutationFourierSum W x χ ρ).im)

private theorem prefixCellMean_eq_of_mem (W j : ℕ) (F : PermΩ W → ℝ)
    (π ρ : PermΩ W) (hρ : ρ ∈ prefixCell W j π) :
    prefixCellMean W j F ρ = prefixCellMean W j F π := by
  have hc : prefixCell W j ρ = prefixCell W j π :=
    (prefixCell_eq_iff_agree W j ρ π).2 (by
      have hρ' : ∀ i : Fin W, i.val < j → ρ i = π i := by
        simpa [prefixCell] using hρ
      intro i hi
      exact hρ' i hi)
  simp [prefixCellMean, hc]

/-- The real cell mean is measurable for the sigma algebra generated by the
revealed prefix. -/
theorem prefixFourierRealMean_measurable (W j : ℕ) (x χ : Fin W → ℂ) :
    Measurable[prefixSigma W j] (prefixFourierRealMean W j x χ) := by
  classical
  change ∀ ⦃s : Set ℝ⦄, MeasurableSet s →
    MeasurableSet[prefixSigma W j]
      ((prefixFourierRealMean W j x χ) ⁻¹' s)
  intro s hs
  let cellUnion : Set (PermΩ W) :=
    ⋃ π : {π : PermΩ W // prefixFourierRealMean W j x χ π ∈ s},
      (prefixCell W j π.1 : Set (PermΩ W))
  have hEq : (prefixFourierRealMean W j x χ) ⁻¹' s = cellUnion := by
    ext ρ
    simp only [cellUnion, Set.mem_iUnion, Set.mem_preimage]
    constructor
    · intro h
      exact ⟨⟨ρ, h⟩, mem_prefixCell W j ρ⟩
    · rintro ⟨π, hρ⟩
      have hval := prefixCellMean_eq_of_mem W j
        (fun ρ => (permutationFourierSum W x χ ρ).re) π.1 ρ hρ
      simpa [prefixFourierRealMean, hval] using π.2
  rw [hEq]
  apply MeasurableSet.iUnion
  intro π
  exact measurableSet_prefixCell W j π.1

/-- The imaginary cell mean is measurable for the sigma algebra generated by
the revealed prefix. -/
theorem prefixFourierImagMean_measurable (W j : ℕ) (x χ : Fin W → ℂ) :
    Measurable[prefixSigma W j] (prefixFourierImagMean W j x χ) := by
  classical
  change ∀ ⦃s : Set ℝ⦄, MeasurableSet s →
    MeasurableSet[prefixSigma W j]
      ((prefixFourierImagMean W j x χ) ⁻¹' s)
  intro s hs
  let cellUnion : Set (PermΩ W) :=
    ⋃ π : {π : PermΩ W // prefixFourierImagMean W j x χ π ∈ s},
      (prefixCell W j π.1 : Set (PermΩ W))
  have hEq : (prefixFourierImagMean W j x χ) ⁻¹' s = cellUnion := by
    ext ρ
    simp only [cellUnion, Set.mem_iUnion, Set.mem_preimage]
    constructor
    · intro h
      exact ⟨⟨ρ, h⟩, mem_prefixCell W j ρ⟩
    · rintro ⟨π, hρ⟩
      have hval := prefixCellMean_eq_of_mem W j
        (fun ρ => (permutationFourierSum W x χ ρ).im) π.1 ρ hρ
      simpa [prefixFourierImagMean, hval] using π.2
  rw [hEq]
  apply MeasurableSet.iUnion
  intro π
  exact measurableSet_prefixCell W j π.1

/-- Real part commutes with the actual finite-cell average. -/
theorem prefixFourierRealMean_eq_re (W j : ℕ) (x χ : Fin W → ℂ)
    (π : PermΩ W) :
    prefixFourierRealMean W j x χ π = (prefixFourierMean W j x χ π).re := by
  classical
  unfold prefixFourierRealMean prefixCellMean prefixFourierMean
  simp only [Complex.div_natCast_re, Complex.re_sum]

/-- Imaginary part commutes with the actual finite-cell average. -/
theorem prefixFourierImagMean_eq_im (W j : ℕ) (x χ : Fin W → ℂ)
    (π : PermΩ W) :
    prefixFourierImagMean W j x χ π = (prefixFourierMean W j x χ π).im := by
  classical
  unfold prefixFourierImagMean prefixCellMean prefixFourierMean
  simp only [Complex.div_natCast_im, Complex.im_sum]

/-- The real-coordinate actual-prefix increment inherits the complex `8/W`
bound. -/
theorem abs_prefixFourierRealMean_increment_le
    (W : ℕ) (hW : 2 ≤ W) (k : Fin W) (x χ : Fin W → ℂ)
    (hx : ∀ i, ‖x i‖ ≤ 2) (hχ : ∀ i, ‖χ i‖ ≤ 1) (π : PermΩ W) :
    |prefixFourierRealMean W (k.val + 1) x χ π -
      prefixFourierRealMean W k.val x χ π| ≤ 8 / (W : ℝ) := by
  rw [prefixFourierRealMean_eq_re, prefixFourierRealMean_eq_re]
  have h := norm_permutationFourierSum_actualPrefix_increment_le
    W hW k x χ hx hχ π
  have hr := Complex.abs_re_le_norm
    (prefixFourierMean W (k.val + 1) x χ π - prefixFourierMean W k.val x χ π)
  rw [Complex.sub_re] at hr
  exact hr.trans h

/-- The imaginary-coordinate actual-prefix increment inherits the complex
`8/W` bound. -/
theorem abs_prefixFourierImagMean_increment_le
    (W : ℕ) (hW : 2 ≤ W) (k : Fin W) (x χ : Fin W → ℂ)
    (hx : ∀ i, ‖x i‖ ≤ 2) (hχ : ∀ i, ‖χ i‖ ≤ 1) (π : PermΩ W) :
    |prefixFourierImagMean W (k.val + 1) x χ π -
      prefixFourierImagMean W k.val x χ π| ≤ 8 / (W : ℝ) := by
  rw [prefixFourierImagMean_eq_im, prefixFourierImagMean_eq_im]
  have h := norm_permutationFourierSum_actualPrefix_increment_le
    W hW k x χ hx hχ π
  have hi := Complex.abs_im_le_norm
    (prefixFourierMean W (k.val + 1) x χ π - prefixFourierMean W k.val x χ π)
  rw [Complex.sub_im] at hi
  exact hi.trans h

/-- Once the full permutation is revealed, the complex Fourier mean is the
original Fourier observable. -/
theorem prefixFourierMean_eq_of_width_le (W j : ℕ) (hWj : W ≤ j)
    (x χ : Fin W → ℂ) (π : PermΩ W) :
    prefixFourierMean W j x χ π = permutationFourierSum W x χ π := by
  classical
  simp [prefixFourierMean, prefixCell_eq_singleton_of_width_le W j hWj π]

/-- Width one has a singleton permutation space, so every prefix mean is
pointwise the original Fourier observable, even at prefix length zero. -/
theorem prefixFourierMean_one (j : ℕ) (x χ : Fin 1 → ℂ) (π : PermΩ 1) :
    prefixFourierMean 1 j x χ π = permutationFourierSum 1 x χ π := by
  classical
  have hcell : prefixCell 1 j π = {π} := by
    ext ρ
    simp only [Finset.mem_singleton]
    constructor
    · intro _
      exact Subsingleton.elim _ _
    · intro h
      subst ρ
      exact mem_prefixCell 1 j π
  simp [prefixFourierMean, hcell]

/-- Explicit width-zero and width-one component checks. Both permutation
spaces are singletons, so all actual prefix means equal the observable. -/
theorem prefixFourierComponents_zero_one
    (j : ℕ) (x₀ χ₀ : Fin 0 → ℂ) (π₀ : PermΩ 0)
    (x₁ χ₁ : Fin 1 → ℂ) (π₁ : PermΩ 1) :
    prefixFourierRealMean 0 j x₀ χ₀ π₀ =
      (permutationFourierSum 0 x₀ χ₀ π₀).re ∧
    prefixFourierImagMean 0 j x₀ χ₀ π₀ =
      (permutationFourierSum 0 x₀ χ₀ π₀).im ∧
    prefixFourierRealMean 1 j x₁ χ₁ π₁ =
      (permutationFourierSum 1 x₁ χ₁ π₁).re ∧
    prefixFourierImagMean 1 j x₁ χ₁ π₁ =
      (permutationFourierSum 1 x₁ χ₁ π₁).im := by
  repeat' constructor
  · rw [prefixFourierRealMean_eq_re,
      prefixFourierMean_eq_of_width_le 0 j (Nat.zero_le j) x₀ χ₀ π₀]
  · rw [prefixFourierImagMean_eq_im,
      prefixFourierMean_eq_of_width_le 0 j (Nat.zero_le j) x₀ χ₀ π₀]
  · rw [prefixFourierRealMean_eq_re, prefixFourierMean_one]
  · rw [prefixFourierImagMean_eq_im, prefixFourierMean_one]

/-- Explicit boundary checks at widths zero and one: every actual prefix mean
is already the fully revealed Fourier observable. -/
theorem prefixFourierMean_zero_one (j : ℕ) (x : Fin 0 → ℂ) (χ : Fin 0 → ℂ)
    (π : PermΩ 0) :
    prefixFourierMean 0 j x χ π = permutationFourierSum 0 x χ π ∧
    prefixFourierMean 1 j (fun _ => (0 : ℂ)) (fun _ => (0 : ℂ))
      (Equiv.refl _) = permutationFourierSum 1 (fun _ => 0) (fun _ => 0)
        (Equiv.refl _) := by
  constructor
  · exact prefixFourierMean_eq_of_width_le 0 j (Nat.zero_le j) x χ π
  · exact prefixFourierMean_one j (fun _ => 0) (fun _ => 0) (Equiv.refl _)

/-- At width two, the stipulated tables give a nonconstant first real reveal:
the zero-prefix mean is zero and the identity first-prefix mean is two. -/
theorem prefixFourierRealMean_two_nonconstant_witness :
    ∃ x χ : Fin 2 → ℂ,
      (∀ i, ‖x i‖ ≤ 2) ∧ (∀ i, ‖χ i‖ ≤ 1) ∧
      prefixFourierRealMean 2 0 x χ (Equiv.refl _) = 0 ∧
      prefixFourierRealMean 2 1 x χ (Equiv.refl _) = 2 := by
  obtain ⟨x, χ, hx, hχ, h0, h1⟩ := prefixFourierMean_two_nonconstant_witness
  refine ⟨x, χ, hx, hχ, ?_, ?_⟩
  · rw [prefixFourierRealMean_eq_re, h0]
    rfl
  · rw [prefixFourierRealMean_eq_re, h1]
    rfl

/-- The final reveal has zero real and imaginary component increments. -/
theorem prefixFourierComponents_last_eq (W : ℕ) (k : Fin W)
    (x χ : Fin W → ℂ) (π : PermΩ W) (hk : k.val + 1 = W) :
    prefixFourierRealMean W (k.val + 1) x χ π =
      prefixFourierRealMean W k.val x χ π ∧
    prefixFourierImagMean W (k.val + 1) x χ π =
    prefixFourierImagMean W k.val x χ π := by
  constructor
  · rw [prefixFourierRealMean_eq_re, prefixFourierRealMean_eq_re,
      prefixFourierMean_last_eq W k x χ π hk]
  · rw [prefixFourierImagMean_eq_im, prefixFourierImagMean_eq_im,
      prefixFourierMean_last_eq W k x χ π hk]

#print axioms prefixFourierRealMean
#print axioms prefixFourierImagMean
#print axioms prefixFourierRealMean_measurable
#print axioms prefixFourierImagMean_measurable
#print axioms prefixFourierRealMean_eq_re
#print axioms prefixFourierImagMean_eq_im
#print axioms abs_prefixFourierRealMean_increment_le
#print axioms abs_prefixFourierImagMean_increment_le
#print axioms prefixFourierMean_eq_of_width_le
#print axioms prefixFourierMean_one
#print axioms prefixFourierComponents_zero_one
#print axioms prefixFourierMean_zero_one
#print axioms prefixFourierRealMean_two_nonconstant_witness
#print axioms prefixFourierComponents_last_eq

end RBM.Gauss
