import RBM1D.Gauss.PermutationPrefixCellMeasurable
import RBM1D.Gauss.PermutationPrefixCellPartition

/-!
Atoms of the finite prefix sigma algebra are exactly the actual prefix cells.
This identifies information sets only; no conditional law is asserted.
-/

namespace RBM.Gauss

open MeasureTheory

/-- The atom of a permutation in the sigma algebra generated by revealed
coordinate cylinders is its actual-prefix cell. -/
theorem measurableAtom_prefixSigma_eq_prefixCell (W k : ℕ) (π : PermΩ W) :
    @measurableAtom (PermΩ W) (prefixSigma W k) π =
      {ρ | ρ ∈ prefixCell W k π} := by
  classical
  letI : MeasurableSpace (PermΩ W) := prefixSigma W k
  apply Set.Subset.antisymm
  · exact measurableAtom_subset (measurableSet_prefixCell W k π)
      (mem_prefixCell W k π)
  · intro ρ hρ
    simp only [Set.mem_ofPred_eq, prefixCell, Finset.mem_filter,
      Finset.mem_univ, true_and] at hρ
    have hgen : ∀ s ∈ prefixCylinders W k, π ∈ s ↔ ρ ∈ s := by
      intro s hs
      obtain ⟨i, v, hik, rfl⟩ := hs
      have heq : ρ i = π i := hρ i hik
      simp only [Set.mem_ofPred_eq]
      rw [heq]
    have hall : ∀ s, MeasurableSet[prefixSigma W k] s →
        (π ∈ s ↔ ρ ∈ s) := by
      exact MeasurableSpace.forall_generateFrom_mem_iff_mem_iff.mpr hgen
    simp only [measurableAtom, Set.mem_iInter]
    intro s hπ hs
    exact (hall s hs).mp hπ

/-- With no coordinates revealed, every prefix atom is the whole space. -/
theorem measurableAtom_prefixSigma_zero (W : ℕ) (π : PermΩ W) :
    @measurableAtom (PermΩ W) (prefixSigma W 0) π = Set.univ := by
  rw [measurableAtom_prefixSigma_eq_prefixCell]
  exact prefixCell_event_eq_univ_of_zero W π

/-- The zero-width prefix atom is the whole (one-point) permutation space. -/
theorem measurableAtom_prefixSigma_zero_width (k : ℕ) (π : PermΩ 0) :
    @measurableAtom (PermΩ 0) (prefixSigma 0 k) π = Set.univ := by
  rw [measurableAtom_prefixSigma_eq_prefixCell]
  ext ρ
  have hρ : ρ = π := Subsingleton.elim _ _
  subst ρ
  simp [mem_prefixCell]

/-- Once every coordinate has been revealed, each prefix atom is a singleton. -/
theorem measurableAtom_prefixSigma_singleton_of_width_le (W k : ℕ)
    (hWk : W ≤ k) (π : PermΩ W) :
    @measurableAtom (PermΩ W) (prefixSigma W k) π = {π} := by
  rw [measurableAtom_prefixSigma_eq_prefixCell]
  exact prefixCell_event_eq_singleton_of_width_le W k hWk π

/-- At width two and prefix zero, identity and swap are distinct members of
the same nonsingleton prefix atom. -/
theorem measurableAtom_prefixSigma_two_support_witness :
    let idPerm : PermΩ 2 := Equiv.refl (Fin 2)
    let swapPerm : PermΩ 2 := Equiv.swap 0 1
    idPerm ∈ @measurableAtom (PermΩ 2) (prefixSigma 2 0) idPerm ∧
      swapPerm ∈ @measurableAtom (PermΩ 2) (prefixSigma 2 0) idPerm ∧
        swapPerm ≠ idPerm := by
  simpa only [measurableAtom_prefixSigma_eq_prefixCell, Set.mem_ofPred_eq] using
    prefixCell_two_support_witness

/-- Identity and swap label the same atom before any coordinate is revealed. -/
theorem measurableAtom_prefixSigma_two_id_swap_eq_zero :
    @measurableAtom (PermΩ 2) (prefixSigma 2 0)
      (Equiv.refl (Fin 2) : PermΩ 2) =
    @measurableAtom (PermΩ 2) (prefixSigma 2 0)
      (Equiv.swap 0 1 : PermΩ 2) := by
  rw [measurableAtom_prefixSigma_zero, measurableAtom_prefixSigma_zero]

/-- Revealing coordinate zero separates identity and swap at width two. -/
theorem measurableAtom_prefixSigma_two_id_swap_ne_one :
    @measurableAtom (PermΩ 2) (prefixSigma 2 1)
      (Equiv.refl (Fin 2) : PermΩ 2) ≠
    @measurableAtom (PermΩ 2) (prefixSigma 2 1)
      (Equiv.swap 0 1 : PermΩ 2) := by
  rw [measurableAtom_prefixSigma_eq_prefixCell,
    measurableAtom_prefixSigma_eq_prefixCell]
  intro h
  apply prefixCell_two_id_swap_ne_one
  ext ρ
  exact Set.ext_iff.mp h ρ

#print axioms measurableAtom_prefixSigma_eq_prefixCell
#print axioms measurableAtom_prefixSigma_zero
#print axioms measurableAtom_prefixSigma_zero_width
#print axioms measurableAtom_prefixSigma_singleton_of_width_le
#print axioms measurableAtom_prefixSigma_two_support_witness
#print axioms measurableAtom_prefixSigma_two_id_swap_eq_zero
#print axioms measurableAtom_prefixSigma_two_id_swap_ne_one

end RBM.Gauss
