import RBM1D.Gauss.PermutationPrefixFiltrationCore

/-!
Measurability of actual finite-permutation prefix cells in the prefix filtration.
This is a finite measurable-set fact only; it asserts no conditional law.
-/

open MeasureTheory

namespace RBM.Gauss

/-- The actual prefix cell is measurable in the sigma algebra generated by its
coordinate cylinders. -/
theorem measurableSet_prefixCell (W k : ℕ) (π : PermΩ W) :
    MeasurableSet[prefixSigma W k] {ρ | ρ ∈ prefixCell W k π} := by
  classical
  have hcell :
      {ρ | ρ ∈ prefixCell W k π} =
        ⋂ i : {i : Fin W // i.val < k}, {ρ | ρ i.1 = π i.1} := by
    ext ρ
    simp [prefixCell]
  rw [hcell]
  apply MeasurableSet.iInter
  intro i
  apply MeasurableSpace.measurableSet_generateFrom
  exact ⟨i.1, π i.1, i.2, rfl⟩

/-- At prefix length zero, the actual prefix-cell event is the whole sample space. -/
theorem prefixCell_event_eq_univ_of_zero (W : ℕ) (π : PermΩ W) :
    {ρ | ρ ∈ prefixCell W 0 π} = Set.univ := by
  classical
  ext ρ
  simp [prefixCell]

/-- Once all coordinates are revealed, the actual prefix-cell event is the
singleton containing its source permutation. -/
theorem prefixCell_event_eq_singleton_of_width_le (W k : ℕ) (hWk : W ≤ k)
    (π : PermΩ W) :
    {ρ | ρ ∈ prefixCell W k π} = {π} := by
  classical
  ext ρ
  simp [prefixCell_eq_singleton_of_width_le W k hWk π]

/-- The zero-width permutation space has exactly one element, and its cell is
that singleton at every prefix length. -/
theorem prefixCell_event_zero_width (k : ℕ) (π : PermΩ 0) :
    {ρ | ρ ∈ prefixCell 0 k π} = {(Equiv.refl (Fin 0) : PermΩ 0)} := by
  have hπ : π = Equiv.refl (Fin 0) := Subsingleton.elim _ _
  rw [prefixCell_event_eq_singleton_of_width_le 0 k (Nat.zero_le k) π, hπ]

/-- Identity and swap both belong to the same nontrivial support cell at `W=2`,
`k=0`; hence the event is not supported at one permutation. -/
theorem prefixCell_event_two_support_witness :
    let idPerm : PermΩ 2 := Equiv.refl (Fin 2)
    let swapPerm : PermΩ 2 := Equiv.swap 0 1
    idPerm ∈ {ρ | ρ ∈ prefixCell 2 0 idPerm} ∧
      swapPerm ∈ {ρ | ρ ∈ prefixCell 2 0 idPerm} ∧ swapPerm ≠ idPerm := by
  simpa using prefixCell_two_support_witness

#print axioms measurableSet_prefixCell
#print axioms prefixCell_event_eq_univ_of_zero
#print axioms prefixCell_event_eq_singleton_of_width_le
#print axioms prefixCell_event_zero_width
#print axioms prefixCell_event_two_support_witness

end RBM.Gauss
