import Mathlib.Probability.UniformOn
import Mathlib.Probability.Process.Filtration

/-!
Finite uniform-permutation sample space, its prefix-revelation filtration, and positive
actual-prefix cells. This core does not assert a conditional distribution.
-/

open MeasureTheory ProbabilityTheory

namespace RBM.Gauss

/-- The finite sample space of permutations of a width-`W` index set. -/
abbrev PermΩ (W : ℕ) := Equiv.Perm (Fin W)

instance permΩMeasurableSpace (W : ℕ) : MeasurableSpace (PermΩ W) := ⊤

/-- The uniform probability measure on all permutations of `Fin W`. -/
noncomputable def uniformPerm (W : ℕ) : Measure (PermΩ W) :=
  ProbabilityTheory.uniformOn (Set.univ : Set (PermΩ W))

instance uniformPerm_isProbabilityMeasure (W : ℕ) : IsProbabilityMeasure (uniformPerm W) := by
  unfold uniformPerm
  infer_instance

/-- A single coordinate event used to generate the information revealed by a prefix. -/
def prefixCylinders (W k : ℕ) : Set (Set (PermΩ W)) :=
  {s | ∃ (i v : Fin W), i.val < k ∧ s = {π | π i = v}}

/-- The sigma algebra generated by the values at positions strictly below `k`. -/
def prefixSigma (W k : ℕ) : MeasurableSpace (PermΩ W) :=
  MeasurableSpace.generateFrom (prefixCylinders W k)

theorem prefixSigma_mono (W : ℕ) : Monotone (prefixSigma W) := by
  intro k l hkl
  unfold prefixSigma
  apply MeasurableSpace.generateFrom_mono
  rintro s ⟨i, v, hi, rfl⟩
  exact ⟨i, v, Nat.lt_of_lt_of_le hi hkl, rfl⟩

/-- The natural-number filtration revealing one more permutation value at each step. -/
def prefixFiltration (W : ℕ) : Filtration ℕ (inferInstance : MeasurableSpace (PermΩ W)) where
  seq := prefixSigma W
  mono' := prefixSigma_mono W
  le' := fun _ => le_top

/-- Permutations agreeing with `π` at all positions below `k`. -/
noncomputable def prefixCell (W k : ℕ) (π : PermΩ W) : Finset (PermΩ W) := by
  classical
  exact Finset.univ.filter (fun ρ => ∀ i : Fin W, i.val < k → ρ i = π i)

theorem mem_prefixCell (W k : ℕ) (π : PermΩ W) : π ∈ prefixCell W k π := by
  classical
  simp [prefixCell]

theorem prefixCell_card_pos (W k : ℕ) (π : PermΩ W) : 0 < (prefixCell W k π).card :=
  Finset.card_pos.mpr ⟨π, mem_prefixCell W k π⟩

/-- With no revealed coordinates, the actual prefix cell is the full permutation space. -/
theorem prefixCell_eq_univ_of_zero (W : ℕ) (π : PermΩ W) :
    prefixCell W 0 π = Finset.univ := by
  classical
  ext ρ
  simp [prefixCell]

/-- Once `k` covers the whole index type, the actual prefix cell is a singleton.
This includes the empty permutation space's unique element when `W=0`. -/
theorem prefixCell_eq_singleton_of_width_le (W k : ℕ) (hWk : W ≤ k)
    (π : PermΩ W) : prefixCell W k π = {π} := by
  classical
  ext ρ
  simp only [prefixCell, Finset.mem_filter, Finset.mem_univ, true_and,
    Finset.mem_singleton]
  constructor
  · intro h
    apply Equiv.ext
    intro i
    exact h i (Nat.lt_of_lt_of_le i.isLt hWk)
  · rintro rfl i hi
    rfl

/-- At `k=0`, both permutations lie in the same actual prefix cell, and are distinct. -/
theorem prefixCell_two_support_witness :
    let idPerm : PermΩ 2 := Equiv.refl (Fin 2)
    let swapPerm : PermΩ 2 := Equiv.swap 0 1
    idPerm ∈ prefixCell 2 0 idPerm ∧
      swapPerm ∈ prefixCell 2 0 idPerm ∧ swapPerm ≠ idPerm := by
  classical
  constructor
  · exact mem_prefixCell 2 0 _
  constructor
  · simp [prefixCell]
  · intro h
    have h01 : Equiv.swap (0 : Fin 2) 1 0 = (0 : Fin 2) :=
      congrArg (fun e : Equiv.Perm (Fin 2) => e 0) h
    have : (1 : Fin 2) = 0 := by simpa using h01
    exact (by decide : (1 : Fin 2) ≠ 0) this

#print axioms PermΩ
#print axioms permΩMeasurableSpace
#print axioms prefixCylinders
#print axioms prefixSigma
#print axioms uniformPerm_isProbabilityMeasure
#print axioms prefixSigma_mono
#print axioms prefixFiltration
#print axioms uniformPerm
#print axioms prefixCell
#print axioms mem_prefixCell
#print axioms prefixCell_card_pos
#print axioms prefixCell_eq_univ_of_zero
#print axioms prefixCell_eq_singleton_of_width_le
#print axioms prefixCell_two_support_witness

end RBM.Gauss
