/-
Copyright (c) 2026 Jun Yin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jun Yin
-/
import Mathlib.LinearAlgebra.Matrix.Circulant
import Mathlib.Data.ZMod.Basic
import Mathlib.Analysis.Matrix.Normed

/-!
# The block covariance matrix `S^(B)`

Formalization of Horng-Tzer Yau and Jun Yin,
*Delocalization of One-Dimensional Random Band Matrices*, Section 2.1.

For a number of blocks `L` the paper sets
`S^(B)_{a b} = (1/3) * 1(dist_{ZMod L}(a, b) ≤ 1)` for `a b : ZMod L`.

Since `dist_{ZMod L}(a, b) ≤ 1` means exactly `a - b ∈ {0, 1, -1}`, this is the
circulant matrix generated by `RBM.sbKernel`.

`S^(B)` is stochastic only when `3 ≤ L`: for `L = 1` the row sums are `1/3`, and
for `L = 2` one has `1 = -1` so the row sums are `2/3`.  The paper leaves this
implicit; here `3 ≤ L` is carried as an explicit hypothesis.  See
`docs/paper-deltas.md`.

## Main results

* `RBM.SB_isSymm`          : symmetry, Lemma 2.14 (1) at the level of `S^(B)`
* `RBM.SB_apply_add_right` : translation invariance, Lemma 2.14 (2)
* `RBM.sum_SB_row`         : the rows of `S^(B)` sum to `1`
* `RBM.SB_mulVec_one`      : `S^(B) 1 = 1`, used repeatedly in Section 3
-/

namespace RBM

open Finset Matrix

section Defs

variable (L : ℕ)

/-- The nearest-neighbour support `{0, 1, -1} ⊆ ZMod L`. -/
def sbSupport : Finset (ZMod L) := {0, 1, -1}

/-- The generating kernel of `S^(B)`: the value `1/3` on `{0, 1, -1}`, zero elsewhere. -/
noncomputable def sbKernel : ZMod L → ℂ :=
  fun u => if u ∈ sbSupport L then (3 : ℂ)⁻¹ else 0

/-- The block covariance matrix `S^(B)` of Section 2.1. -/
noncomputable def SB : Matrix (ZMod L) (ZMod L) ℂ := circulant (sbKernel L)

theorem SB_apply (a b : ZMod L) : SB L a b = sbKernel L (a - b) := rfl

end Defs

section Symmetry

variable (L : ℕ)

theorem neg_mem_sbSupport {u : ZMod L} : -u ∈ sbSupport L ↔ u ∈ sbSupport L := by
  simp only [sbSupport, Finset.mem_insert, Finset.mem_singleton, neg_eq_iff_eq_neg,
    neg_zero, neg_neg]
  tauto

theorem sbKernel_neg (u : ZMod L) : sbKernel L (-u) = sbKernel L u := by
  simp only [sbKernel]
  exact if_congr (neg_mem_sbSupport L) rfl rfl

/-- Lemma 2.14 (1) at the level of `S^(B)`: symmetry. -/
theorem SB_isSymm : (SB L).IsSymm := by
  rw [SB, circulant_isSymm_iff]
  exact sbKernel_neg L

theorem SB_transpose : (SB L)ᵀ = SB L := SB_isSymm L

/-- Lemma 2.14 (2) at the level of `S^(B)`: translation invariance. -/
theorem SB_apply_add_right (a b c : ZMod L) : SB L (a + c) (b + c) = SB L a b := by
  simp only [SB_apply, add_sub_add_right_eq_sub]

end Symmetry

section Char

variable (L : ℕ)

theorem one_ne_zero_zmod (hL : 3 ≤ L) : (1 : ZMod L) ≠ 0 := by
  have h : ((1 : ℕ) : ZMod L) ≠ 0 := by
    rw [Ne, CharP.cast_eq_zero_iff (ZMod L) L 1]
    intro hdvd
    have := Nat.le_of_dvd Nat.one_pos hdvd
    omega
  simpa using h

theorem two_ne_zero_zmod (hL : 3 ≤ L) : (2 : ZMod L) ≠ 0 := by
  have h : ((2 : ℕ) : ZMod L) ≠ 0 := by
    rw [Ne, CharP.cast_eq_zero_iff (ZMod L) L 2]
    intro hdvd
    have := Nat.le_of_dvd (by norm_num) hdvd
    omega
  simpa using h

/-- For `3 ≤ L` the three lattice points `0, 1, -1` of `ZMod L` are distinct. -/
theorem card_sbSupport (hL : 3 ≤ L) : (sbSupport L).card = 3 := by
  have h1 : (1 : ZMod L) ≠ 0 := one_ne_zero_zmod L hL
  have h2 : (2 : ZMod L) ≠ 0 := two_ne_zero_zmod L hL
  have hm1 : (1 : ZMod L) ≠ -1 := fun h => h2 (by linear_combination h)
  have h0m1 : (0 : ZMod L) ≠ -1 := fun h => h1 (by linear_combination h)
  have h01 : (0 : ZMod L) ≠ 1 := fun h => h1 h.symm
  rw [sbSupport, Finset.card_insert_of_notMem (by simp [h01, h0m1]),
    Finset.card_insert_of_notMem (by simp [hm1]), Finset.card_singleton]

end Char

section Stochastic

variable (L : ℕ) [NeZero L]

/-- Total mass of the generating kernel is `1`, for `3 ≤ L`. -/
theorem sum_sbKernel (hL : 3 ≤ L) : ∑ u : ZMod L, sbKernel L u = 1 := by
  classical
  simp only [sbKernel]
  rw [Finset.sum_ite_mem, Finset.univ_inter, Finset.sum_const, card_sbSupport L hL]
  norm_num

/-- Each row of `S^(B)` sums to `1`. -/
theorem sum_SB_row (hL : 3 ≤ L) (a : ZMod L) : ∑ b : ZMod L, SB L a b = 1 := by
  have h : ∑ b : ZMod L, SB L a b = ∑ u : ZMod L, sbKernel L u := by
    refine Fintype.sum_equiv (Equiv.subLeft a) _ _ ?_
    intro b
    simp [SB_apply]
  rw [h, sum_sbKernel L hL]

/-- `S^(B) 1 = 1`.  Used in (3.47) and in Step 4 of the proof of Lemma 3.6. -/
theorem SB_mulVec_one (hL : 3 ≤ L) : SB L *ᵥ (1 : ZMod L → ℂ) = 1 := by
  funext a
  simp only [Matrix.mulVec, dotProduct, Pi.one_apply, mul_one]
  exact sum_SB_row L hL a

end Stochastic

end RBM
